budgetsapp/urls.py
from django.urls import path
from . import views
from expensesapp import views as expenses_views

app_name = 'presupuestos'

urlpatterns = [
	path('',views.ListBudget.as_view(),name='all'),
	path('create/',views.CreateBudget.as_view(),name='create'),
	path('<int:pk>/gastos/create/',expenses_views.CreateExpense.as_view(),name='create_expense'),
	path('update/<int:pk>/',views.UpdateBudget.as_view(),name='update'),
	path('delete/<int:pk>/',views.DeleteBudget.as_view(),name='delete'),
	path('<int:pk>/',views.BudgetDetail.as_view(),name='detail'),
	path('<int:pk>/summary/',views.BudgetDetailTiny.as_view(),name='detail_summary'),
]

expensesapp/urls.py
from django.urls import path
from expensesapp import views

app_name = 'gastos'

urlpatterns = [
	path('update/<int:pk>/',views.UpdateExpense.as_view(),name='update_expense'),
	path('delete/<int:pk>/',views.DeleteExpense.as_view(),name='delete_expense'),
	path('ajax/pay_expense/',views.pay_expense,name='pay_expense'),
	#path('create/',views.CreateExpense.as_view(),name='_create_'),
	#path('expense/create/',views.CreateExpense.as_view(),name='create_expense'),
	#path('<int:pk>/',views.BudgetDetail.as_view(),name='detail'),

]

loanapp/urls.py
from django.urls import path
from loanapp import views

app_name = 'loans'

urlpatterns = [
	path('',views.AboutView.as_view()),
	path('test',views.LoanView.as_view()),
	path('calculadora_uva/',views.LoanQueryView.as_view(), {'cuota':0, 'saldo':0}, name='calculadora'),
	path('clear-cookies', views.clear_cookies),
]

misgastos/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('new/',views.NewHomePage.as_view(),name='new_home'),
    path('accounts/',include('accountsapp.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path("presupuestos/", include("budgetsapp.urls", namespace="presupuestos")),
    path("gastos/", include("expensesapp.urls", namespace="gastos")),
    path("categorias/", include("categoriesapp.urls", namespace="categorias")),
    path("coffees/", include("coffeeApp.urls", namespace="coffee")),
    path("telegramapi/", include("telegramapi.urls", namespace="telegramapi")),
    path("inversiones/", include("investmentapp.urls", namespace="inversiones")),

    path("loans/", include("loanapp.urls", namespace="loans")),
]

expensesapp/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from budgetsapp.models import Budget
from categoriesapp.models import Category

from django.db.utils import OperationalError

class Expense(models.Model):

	category = models.ForeignKey(	Category,
									related_name='categories',
									on_delete=models.PROTECT)	

	name = models.CharField(max_length=100)
	amount = models.FloatField()
	cantidad_total = models.PositiveIntegerField(default=1)
	cantidad_pendiente = models.PositiveIntegerField(default=0)
	gasto = models.BooleanField(default=True)
	tarjeta_credito = models.BooleanField(default=False)
	budget = models.ForeignKey(Budget,related_name='expenses',null=True, blank=True,on_delete=models.PROTECT)
	skip = models.BooleanField(default=False)

	@property
	def total_amount(self):
		return round(self.amount * self.cantidad_total, 2)

	@property
	def pending_amount(self):
		return round(self.amount * self.cantidad_pendiente,2)

	@property
	def is_paid(self):
		return self.cantidad_pendiente == 0

	@property
	def get_amount(self):
		return self.total_amount - self.pending_amount

	@property
	def is_credit_card(self):
		return self.tarjeta_credito

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('presupuestos:detail',kwargs={'pk':self.budget.pk})

	def __init__(self,*args,**kwargs):
		super().__init__(*args, **kwargs)

expensesapp/forms.py
from django import forms
from expensesapp.models import Expense
from categoriesapp.models import Category

from django.contrib.auth.models import User

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ('name','category','cantidad_total','cantidad_pendiente','amount','gasto', 'tarjeta_credito', 'skip')
        
    def __init__(self,*args,**kwargs):
        self.user = kwargs.pop('user')  # To get request.user. Do not use kwargs.pop('user', None) due to potential security hole
        super().__init__(*args, **kwargs)
        # Cristhian:
        # Label in the HTML
        # Optional
        query_set = User.objects.filter(username='admin')
        admin_pk = query_set[0].pk
        self.fields['name'].label = 'Nombre'
        self.fields['category'].label = 'Categoria'
        self.fields["category"].queryset = (
                     Category.objects.filter(
                      user__in=[self.user.pk,admin_pk]
                  ).order_by('name')
        )
        
        #querySet = Category.objects.filter(name="Impuestos")
        #if len(querySet) > 0: 
        #    pk = querySet[0].pk
        #    self.fields["category"].initial = pk
       

    def clean_cantidad_total(self):
        data = self.cleaned_data['cantidad_total']
        cantidad_pendiente = int(self.data['cantidad_pendiente'])
        if cantidad_pendiente > data:
            raise forms.ValidationError("Cantidad_pendiente no puede ser mayor a Cantidad Total")

        return data

expensesapp/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from expensesapp import forms
from expensesapp.models import Expense
from budgetsapp.models import Budget

from django.http import JsonResponse

from django.db.models import Count

from django.core.exceptions import PermissionDenied

# Create your views here.
class CreateExpense(LoginRequiredMixin,generic.CreateView):
	form_class = forms.ExpenseForm
	model = Expense

	def form_valid(self,form):
		self.object = form.save(commit=False)
		self.object.user = self.request.user
		self.object.budget = Budget.objects.get(pk=self.kwargs.get('pk'))
		self.object.amount = round(self.object.amount, 2)

		querySet = Expense.objects.filter(name__iexact=self.object.name).filter(budget__exact=self.object.budget)
		if len(querySet) > 0:
			form.add_error("name", 'Ya existe un gasto con este nombre')
			return super().form_invalid(form)	

		self.object.save()
		return super().form_valid(form)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs.update({'user': self.request.user})
		return kwargs

	def get_context_data(self, **kwargs):
	 	context = super().get_context_data(**kwargs)
	 	all_expenses = Expense.objects.all()
	 	most_common_expenses = Expense.objects.values('name').annotate(number_of_entries=Count('name')).order_by('-number_of_entries')[:5]
	 	#most_common_expenses = Expense.objects.annotate(number_of_entries=Count('name')).order_by('number_of_entries')

	 	common_expenses = []

	 	for common_expense in most_common_expenses:
	 		for expense in all_expenses:
	 			if expense.name == common_expense['name']:
	 				common_expenses.append(expense)
	 				break
	 	

	 	context['common_expenses'] = common_expenses[:5]

	 	return context


class UpdateExpense(LoginRequiredMixin,UserPassesTestMixin,generic.UpdateView):
	form_class = forms.ExpenseForm
	model = Expense		
	exclude = ('budget',)

	def test_func(self):
		expenses = Expense.objects.filter(pk__exact=self.kwargs.get('pk'))
		if len(expenses) == 1:
			myexpense = expenses[0]

			if myexpense.budget.user.username == self.request.user.username:
				return True

		raise PermissionDenied("You are not authenticated to edit this.")

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs.update({'user': self.request.user})
		return kwargs

class DeleteExpense(LoginRequiredMixin,UserPassesTestMixin,generic.DeleteView):
	model = Expense
	#select_related = ('user','group')
	success_url = reverse_lazy('home')

	def test_func(self):
		expenses = Expense.objects.filter(pk__exact=self.kwargs.get('pk'))
		if len(expenses) == 1:
			myexpense = expenses[0]

			if myexpense.budget.user.username == self.request.user.username:
				return True

		raise PermissionDenied("You are not authenticated to edit this.")

	def get_queryset(self):
		queryset = super().get_queryset()
		return queryset.filter(pk=self.kwargs.get('pk'))

	# TODO: Fix this! 20210329
	def get_success_url__(self):
		next_url = self.request.POST.get('next', 'home')
		print(next_url)
		return HttpResponseRedirect(next_url)
		#return reverse_lazy(next_url)
		#return reverse(next_url)

	def delete(self,*args,**kwargs):
		#messages.success(self.request,'Post Deleted')

		return super().delete(*args,**kwargs)

import time
from django.http import HttpResponseForbidden

def pay_expense(request):
	if not request.user.is_authenticated:
		return HttpResponseForbidden()

	myid = request.POST['myid']
	if myid == -1:
		data = {
			'ajax_answer': False
		}
	else:
		currentExpense = Expense.objects.get(pk=myid)

		if currentExpense.budget.user.username != request.user.username:
			return HttpResponseForbidden()

		currentExpense.cantidad_pendiente -= 1
		currentExpense.save()

		data = {
				'ajax_answer': True,
				'cantidad_pendiente': currentExpense.cantidad_pendiente
		}

	return JsonResponse(data)

expensesapp/templates/expensesapp/expense_confirm_delete.html
{% extends "budgetsapp/budget_base.html" %}

{% block group_content %}
	<h3>¿Seguro desea borrar ?</h3>

	<form method="POST">
		{% csrf_token %}
		<input type="submit" class="btn btn-danger btn-large" value="Confirm Delete">
		<input type="hidden" name="next" value="{% url 'presupuestos:detail' pk=expense.budget.pk %}">
		<a class='btn btn-info btn-large' href="{% url 'presupuestos:detail' pk=expense.budget.pk %}">Cancel</a>
	</form>

{% endblock %}

expensesapp/templates/expensesapp/expense_form.html
{% extends "budgetsapp/budget_base.html" %}
{% load bootstrap3 %}
{% load static %}

{% block content %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6 order-md-1">
				{% if expense.pk != null  %}
					<h4>Actualizar gasto</h4>
				{% else %}
					<h4>Crear un nuevo gasto</h4>
				{% endif %}	
				<form method="POST" id="myForm">
					{% csrf_token %}
					{% bootstrap_form form %}
					
					{% if expense.pk != null  %}
						<input type="submit" class='btn btn-primary btn-large' value="Actualizar">
					{% else %}
						<input type="submit" class='btn btn-primary btn-large' value="Crear">
					{% endif %}	
				</form>
			</div>

			<div class="col order-1">
				<div class="container col-6">
					{% if common_expenses is not None %}
						<h4>Gastos más comunes</h4>
					{% endif %}
					<br>
					<div class="list-group">
						{% for expense in common_expenses %}
							<div class="list-group-item list-group-item-action d-flex w-100 justify-content-between">
						    	<h5 class="mb-1">{{ expense.name }}</h5>
						    </div> 
							<!-- <a href="#" class="list-group-item list-group-item-action">
						    	<div class="d-flex w-100 justify-content-between">
						      		<h5 class="mb-1">{{ expense.name }}</h5>
						    	</div>
						 	</a> -->
						    <br>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script>
    	var static_url = "{% url 'categorias:create' %}";
    	var dict = {};
    	{% for expense in common_expenses %}
    		name = "{{expense.name}}";
    		category = "{{expense.category.name}}";
    		dict[name] = category;
    	{% endfor %}
		
    	$("#id_amount").attr( "step", ".01" );

    	function clean(){
    		$('.list-group-item').each(function( index ) {
	  			if( $( this )[0].classList.contains('active') ) {
	  				$( this ).removeClass('active');
	  			}
	  			$('#id_name').val("");
			});

    	}

    	$("#id_tarjeta_credito").change(function() {
		    if(this.checked) {
		        $("#id_gasto")[0].checked = true
		    }
		});

		$("#id_gasto").change(function() {
		    if(!this.checked) {
		        $("#id_tarjeta_credito")[0].checked = false
		    }
		});


    	$('.list-group-item').on('click', function() {
    		if( $( this )[0].classList.contains('active') ) {
    			$( this ).removeClass('active');
    			var $children = $(this).children('h5');
			    $('#id_name').val("");
    		}
    		else {
	    		clean();
			    var $this = $(this);
			    var $children = $this.children('h5');
			    $this.toggleClass('active')
			    $('#id_name').val($children.text());
			    //$('#id_category')
			    $('#id_category > option').each( function ()  {
			    	if ( $(this).text() == dict[$children.text()] ) {
			    		value = $(this).val();
			    		$('#id_category').val(value);
			    	}
			    });
			    //console.log(dict[$children.text()])
    		}
		});

		//$('#id_name').on('click', function myFunction() {
		//  clean();
		  //var x = $(this).val();
		  //console.log("You wrote: " + x);
		//});
	</script>
	<!-- Script to add + button on the webpage -->
	<script src="{% static 'misgastos/js/expense_form.js' %}" type="text/javascript" ></script>
{% endblock %}