investmentapp/urls.py
from django.urls import path
from investmentapp import views

app_name = 'inversiones'

urlpatterns = [
	path('',views.ListInvestment.as_view(),name='all'),
	path('afluenta/',views.ListInvestmentAfluenta.as_view(),name='afluenta'),
	path('create/',views.CreateInvestment.as_view(),name='create'),
	path('update/<int:pk>/',views.UpdateInvestment.as_view(),name='update'),
	path('delete/<int:pk>/',views.DeleteInvestment.as_view(),name='delete'),
	path('ajax/update_investments/',views.update_investments,name='update_investments'),
]

loanapp/urls.py
from django.urls import path
from loanapp import views

app_name = 'loans'

urlpatterns = [
	path('',views.AboutView.as_view()),
	path('test',views.LoanView.as_view()),
	path('calculadora_uva/',views.LoanQueryView.as_view(), {'cuota':0, 'saldo':0}, name='calculadora'),
	path('clear-cookies', views.clear_cookies),
]

misgastos/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('new/',views.NewHomePage.as_view(),name='new_home'),
    path('accounts/',include('accountsapp.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path("presupuestos/", include("budgetsapp.urls", namespace="presupuestos")),
    path("gastos/", include("expensesapp.urls", namespace="gastos")),
    path("categorias/", include("categoriesapp.urls", namespace="categorias")),
    path("coffees/", include("coffeeApp.urls", namespace="coffee")),
    path("telegramapi/", include("telegramapi.urls", namespace="telegramapi")),
    path("inversiones/", include("investmentapp.urls", namespace="inversiones")),

    path("loans/", include("loanapp.urls", namespace="loans")),
]

loanapp/models.py
from django.db import models

# Create your models here.
class Loan(models.Model):
	amount_cuota = models.FloatField()
	amount_deuda = models.FloatField()
	
	def get_absolute_url(self):
		return reverse('home')

	def __str__(self):
		return 'LoanModel'

loanapp/forms.py
from django import forms

from .models import Loan

class LoanForm(forms.ModelForm):

    class Meta:
        model = Loan
        fields = ('amount_cuota','amount_deuda')


    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        self.fields['amount_cuota'].label = 'Monto Cuota ( UVA )'
        self.fields['amount_deuda'].label = 'Monto Deuda ( UVA )'

loanapp/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView, FormView

from loanapp import forms
from loanapp.models import Loan

from investmentapp.models import Conversion

class AboutView(TemplateView):
    template_name = "loanapp/dashboard.html"
    #template_name = "loanapp/about.html"

class LoanView(FormView):
    model = Loan
    template_name = 'loanapp/loan_form.html'
    form_class = forms.LoanForm
    success_url = "loanapp/about.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        conversion_list = Conversion.objects.filter(name__iexact='UVA')
        if len(conversion_list) == 1:
            uva_conversion = conversion_list[0]

        context['uva'] = uva_conversion.last_quote
        return context

    def _render_to_response(self, context, **response_kwargs):
        response = super(FormView, self).render_to_response(context, **response_kwargs)
        print(context)
        response.set_cookie('CC', 'MyCookie')
        return response

class LoanQueryView(FormView):
    model = Loan
    template_name = 'loanapp/loan_form.html'
    form_class = forms.LoanForm
    success_url = "loanapp/about.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #conversion_list = Conversion.objects.filter(name__iexact='UVA')
        #if len(conversion_list) == 1:
        #    uva_conversion = conversion_list[0]

        #context['uva'] = uva_conversion.last_quote

        #list_of_cookies = self.request.COOKIES
        #for cookie in list_of_cookies:
        #    print(cookie)

        all_conversion_index = Conversion.objects.all()
        uva_quote = 0.0
        blue_quote = 0.0
        green_quote = 0.0
        for conversion_obj in all_conversion_index:
            if conversion_obj.name == 'UVA':
                context['uva'] = conversion_obj.last_quote
                uva_quote = conversion_obj.last_quote

            if conversion_obj.name == 'ARS':
                context['USD_Blue'] = conversion_obj.last_quote
                blue_quote = conversion_obj.last_quote

            if conversion_obj.name == 'ARS_USD_Oficial':
                context['USD'] = conversion_obj.last_quote
                green_quote = conversion_obj.last_quote

        if self.request.GET.get('cuota') :
            # I have receieved on URL
            context['cuota'] = self.request.GET.get('cuota')
            context['cuota_calculada'] = float(self.request.GET.get('cuota')) * uva_quote
        elif self.request.COOKIES.get('_cuota__') and self.request.COOKIES.get('_cuota__') != "undefined":
            context['cuota'] = self.request.COOKIES.get('_cuota__')
            context['cuota_calculada'] = float(self.request.COOKIES.get('_cuota__')) * uva_quote
        else:
            context['cuota'] = 0.0
            context['cuota_calculada'] = 0.0

        if self.request.GET.get('saldo'):
            # I have receieved on URL
            context['saldo'] = self.request.GET.get('saldo')
            context['saldo_calculado_usd'] = float(self.request.GET.get('saldo')) * uva_quote / green_quote
            context['saldo_calculado_usd_blue'] = float(self.request.GET.get('saldo')) * uva_quote / blue_quote
        elif self.request.COOKIES.get('_deuda__') and self.request.COOKIES.get('_deuda__') != "undefined":
            context['saldo'] = self.request.COOKIES.get('_deuda__')
            context['saldo_calculado_usd'] = float(self.request.COOKIES.get('_deuda__')) * uva_quote / green_quote
            context['saldo_calculado_usd_blue'] = float(self.request.COOKIES.get('_deuda__')) * uva_quote / blue_quote
        else:
            context['saldo'] = 0.0
            context['saldo_calculado_usd'] = 0.0
            context['saldo_calculado_usd_blue'] = 0.0
        
        context['conversion_object_list'] = Conversion.objects.exclude(name__contains='BTC').exclude(name__iexact='USDC')

        return context

from django.http import HttpResponseRedirect
def clear_cookies(request):
    response = HttpResponseRedirect('/')
    response.delete_cookie('_deuda__')
    response.delete_cookie('_cuota__')
    return response

loanapp/templates/loanapp/about.html
{% extends "budgetsapp/budget_base.html" %}

{% block pregroup %}
	<div class="col">
		<div class="content">
			<h3>This is the about page!</h3>
		</div>	
	</div>
	
{% endblock %}

{% block postgroup %}

	<h1>postgroup</h1>

 {% endblock %}

loanapp/templates/loanapp/loan_form.html
{% extends "budgetsapp/budget_base.html" %}
{% load bootstrap3 %}


{% block pregroup %}
	<div class="col">
		<div class="content">
			<h3>{{msg_debug}}</h3>
			<form action="" method="POST">
				{% csrf_token %}
				{% bootstrap_form form %}
			</form>
			</br>
			<button onclick="calculate()" class='btn btn-primary btn-large'>Calcular</button>
		</div>	
	</div>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script>

		function setCookie(cname,cvalue,exdays) {
		  const d = new Date();
		  d.setTime(d.getTime() + (exdays*24*60*60*1000));
		  let expires = "expires=" + d.toUTCString();
		  document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
		}

		function getCookie(cname) {
			let name = cname + "=";
			let ca = document.cookie.split(';');
			for(let i = 0; i < ca.length; i++) {
				let c = ca[i];
				while (c.charAt(0) == ' ') {
					c = c.substring(1);
				}
				if (c.indexOf(name) == 0) {
					return c.substring(name.length, c.length);
				}
			}
			return "";
		}

		function calculate() {
			var cuota = $("#id_amount_cuota").val();
			var deuda = $("#id_amount_deuda").val();

			if( (cuota != "") && ( deuda != "")){
				setCookie("_deuda__", deuda, 30);
				setCookie("_cuota__", cuota, 30);
				url = "{% url 'loans:calculadora' %}" + "?cuota=" + cuota + "&saldo=" + deuda
				location.href = url;
			}
		}

		function initialize() {

			$("#id_amount_cuota").val({{ cuota }})
			$("#id_amount_deuda").val({{ saldo }})

			$("#amount_ars").html('ARS: {{ cuota_calculada|floatformat:2 }}')
			$("#amount_usd_blue").html('USD ( Blue ): {{ saldo_calculado_usd_blue|floatformat:2 }}')
			$("#amount_usd").html('USD ( Oficial ): {{ saldo_calculado_usd|floatformat:2 }}')


			if($("#id_amount_deuda").val() == 0)
			{
				$("#id_amount_deuda").val(getCookie("_deuda__"))
			}

			if($("#id_amount_cuota").val() == 0)
			{
				$("#id_amount_cuota").val(getCookie("_cuota__"))
			}
		}

    function updateInvestments(){
      $.ajax({
                  type:"POST",
                  url: "{% url 'inversiones:update_investments'%}",
                  data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                  },
                  dataType: 'json'
                });
    }
    

  //   window.setInterval(function() {
  //   	initialize();
  //  		updateInvestments()
		// }, 1000 * 60 * 5);

		window.setTimeout( function() {
			console.log("Calling reload()")
  		window.location.reload();
		}, 1000 * 60 * 5);

	</script>

{% endblock %}

{% block postgroup %}

	<div class="col order-1">
	  </br>
	  <div class="alert alert-success" id="amount_ars" role="alert">
	      ARS: 
	  </div>
	  </br>
	  <div class="alert alert-success" id="amount_usd" role="alert">
	    USD ( Oficial ): 
	  </div>
	  </br>
	  <div class="alert alert-success" id="amount_usd_blue" role="alert">
	    USD ( Blue ): 
	  </div>
	</div>

	<div class="col-md-6 col-xxl-3">
      <div class="card h-md-100 ecommerce-card-min-width">
        <div class="card-header pb-0">
          <h6 class="mb-0 mt-2 d-flex align-items-center">Weekly Sales<span class="ms-1 text-400" data-bs-toggle="tooltip" data-bs-placement="top" aria-label="Calculated according to last week's sales"><svg class="svg-inline--fa fa-question-circle fa-w-16" data-fa-transform="shrink-1" aria-hidden="true" focusable="false" data-prefix="far" data-icon="question-circle" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg="" style="transform-origin: 0.5em 0.5em;"><g transform="translate(256 256)"><g transform="translate(0, 0)  scale(0.9375, 0.9375)  rotate(0 0 0)"><path fill="currentColor" d="M256 8C119.043 8 8 119.083 8 256c0 136.997 111.043 248 248 248s248-111.003 248-248C504 119.083 392.957 8 256 8zm0 448c-110.532 0-200-89.431-200-200 0-110.495 89.472-200 200-200 110.491 0 200 89.471 200 200 0 110.53-89.431 200-200 200zm107.244-255.2c0 67.052-72.421 68.084-72.421 92.863V300c0 6.627-5.373 12-12 12h-45.647c-6.627 0-12-5.373-12-12v-8.659c0-35.745 27.1-50.034 47.579-61.516 17.561-9.845 28.324-16.541 28.324-29.579 0-17.246-21.999-28.693-39.784-28.693-23.189 0-33.894 10.977-48.942 29.969-4.057 5.12-11.46 6.071-16.666 2.124l-27.824-21.098c-5.107-3.872-6.251-11.066-2.644-16.363C184.846 131.491 214.94 112 261.794 112c49.071 0 101.45 38.304 101.45 88.8zM298 368c0 23.159-18.841 42-42 42s-42-18.841-42-42 18.841-42 42-42 42 18.841 42 42z" transform="translate(-256 -256)"></path></g></g></svg><!-- <span class="far fa-question-circle" data-fa-transform="shrink-1"></span> Font Awesome fontawesome.com --></span></h6>
        </div>
        <div class="card-body d-flex flex-column justify-content-end">
          <div class="row">
            <div class="col">
              <p class="font-sans-serif lh-1 mb-1 fs-4">$47K</p><span class="badge badge-soft-success rounded-pill fs--2">+3.5%</span>
            </div>
        </div>
      </div>
    </div>

	<script type="text/javascript">initialize();</script> 

 {% endblock %}

{% block footer %} 
 <div class="container-fluid">
    <h3>Conversion</h3>
    <table class="table table-striped order-list">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nombre</th>
          <th scope="col">Última Actualización</th>
          <th scope="col">Último Valor</th>
          <th scope="col">Activo para elegir</th>
        </tr>
      </thead>
      <tbody>
        {% for conversion_obj in conversion_object_list %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ conversion_obj.name }}</td>
            <td>{{ conversion_obj.last_update }}</td>
            <td>{{ conversion_obj.last_quote }}</td>
            <td>{{ conversion_obj.active_for_selection }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}