accountsapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accountsapp'

urlpatterns = [
	path('login/',auth_views.LoginView.as_view(template_name='accountsapp/login.html'), name='login'),
	path('change-password/',auth_views.PasswordChangeView.as_view(template_name='accountsapp/change-password.html', success_url='/'), name='change_password'),
	path('logout/',auth_views.LogoutView.as_view(), name='logout'),
	path('signup/',views.SignUpView.as_view(), name='signup'),
	#path('update_profile/<int:pk>/',views.UpdateProfile.as_view(), name='update_profile'),
	path('update_profile/',views.UpdateProfile.as_view(), name='update_profile'),
	path('create_profile/',views.CreateProfile.as_view(), name='create_profile'),
	path('list_profile/',views.ListProfile.as_view(),name='list_profile')
]

coffeeApp/urls.py
from django.urls import path
from coffeeApp import views

app_name = 'coffee'

urlpatterns = [
	path('',views.CoffeeList.as_view(),name='all'),
	path('json/',views.CoffeeListJSON.as_view(),name='all_json'),
	path('<int:pk>',views.CoffeeDetail.as_view(),name='single'),
	path('<int:pk>.json',views.CoffeeDetailJSON.as_view(),name='single_json'),
]

loanapp/urls.py
from django.urls import path
from loanapp import views

app_name = 'loans'

urlpatterns = [
	path('',views.AboutView.as_view()),
	path('test',views.LoanView.as_view()),
	path('calculadora_uva/',views.LoanQueryView.as_view(), {'cuota':0, 'saldo':0}, name='calculadora'),
	path('clear-cookies', views.clear_cookies),
]

misgastos/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('new/',views.NewHomePage.as_view(),name='new_home'),
    path('accounts/',include('accountsapp.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path("presupuestos/", include("budgetsapp.urls", namespace="presupuestos")),
    path("gastos/", include("expensesapp.urls", namespace="gastos")),
    path("categorias/", include("categoriesapp.urls", namespace="categorias")),
    path("coffees/", include("coffeeApp.urls", namespace="coffee")),
    path("telegramapi/", include("telegramapi.urls", namespace="telegramapi")),
    path("inversiones/", include("investmentapp.urls", namespace="inversiones")),

    path("loans/", include("loanapp.urls", namespace="loans")),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Cantero Solutions!</title>

	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
	
	<!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet"> -->
	<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>

	<!-- Bootstrap  -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	<!-- Own css file  -->
	<link rel="stylesheet" href="{% static 'misgastos/css/master.css' %}">

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark techfont mynav" id='navbar'>
		<a class='navbar-brand mynav' href="{% url 'home' %}">Cantero Solutions!</a>
		<ul class='nav navbar-nav navbar-right ml-auto'>
			{% if user.is_authenticated %}
				{% if user.profile.telegram_user == "" %}
					<li><a class="nav-link" href="{% url 'accountsapp:create_profile' %}" >Link Telegram </a></li>
				{% else %}
					<li><a class="nav-link">Linked with Telegram </a></li>
				{% endif %}	

				<li><a class="nav-link" href="{% url 'loans:calculadora' %}">Caluladora UVA</a></li>
				<li><a class="nav-link" href="{% url 'presupuestos:all' %}">Mis presupuestos</a></li>
				<li><a class="nav-link" href="{% url 'inversiones:all' %}">Mis inversiones</a></li>
				<li><a class="nav-link" href="{% url 'accountsapp:change_password' %}" >Cambiar password</a></li>
				<li><a class="nav-link" href="{% url 'accountsapp:logout' %}" >Log Out</a></li>
			{% else %}
				<li><a class="nav-link" href="{% url 'loans:calculadora' %}">Caluladora UVA</a></li>
				<li><a class="nav-link" href="{% url 'accountsapp:login' %}">Identificate</a></li>
				<li><a class="nav-link" href="{% url 'accountsapp:signup' %}">Registrate</a></li>
			{% endif %}
		</ul>

	</nav>

	<div class="container-fluid">
		{% block content %}

		{% endblock %}
	</div>

</body>
<script src="{% static "misgastos/js/master.js"%}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

	<h1>Bienvenido a Cantero Solutions!</h1>
	{# {% include "budgetsapp/budget_list.html" %} #}

{% endblock %}

templates/new_index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Dashboard Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/dashboard/">

    <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'misgastos/css/dashboard.css' %}">

  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Sign out</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="#">
              <span data-feather="home"></span>
              Dashboard <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Orders
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="d-flex align-items-center text-muted" href="#">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>

      <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

      <h2>Section title</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>Lorem</td>
              <td>ipsum</td>
              <td>dolor</td>
              <td>sit</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>amet</td>
              <td>consectetur</td>
              <td>adipiscing</td>
              <td>elit</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>Integer</td>
              <td>nec</td>
              <td>odio</td>
              <td>Praesent</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>libero</td>
              <td>Sed</td>
              <td>cursus</td>
              <td>ante</td>
            </tr>
            <tr>
              <td>1,004</td>
              <td>dapibus</td>
              <td>diam</td>
              <td>Sed</td>
              <td>nisi</td>
            </tr>
            <tr>
              <td>1,005</td>
              <td>Nulla</td>
              <td>quis</td>
              <td>sem</td>
              <td>at</td>
            </tr>
            <tr>
              <td>1,006</td>
              <td>nibh</td>
              <td>elementum</td>
              <td>imperdiet</td>
              <td>Duis</td>
            </tr>
            <tr>
              <td>1,007</td>
              <td>sagittis</td>
              <td>ipsum</td>
              <td>Praesent</td>
              <td>mauris</td>
            </tr>
            <tr>
              <td>1,008</td>
              <td>Fusce</td>
              <td>nec</td>
              <td>tellus</td>
              <td>sed</td>
            </tr>
            <tr>
              <td>1,009</td>
              <td>augue</td>
              <td>semper</td>
              <td>porta</td>
              <td>Mauris</td>
            </tr>
            <tr>
              <td>1,010</td>
              <td>massa</td>
              <td>Vestibulum</td>
              <td>lacinia</td>
              <td>arcu</td>
            </tr>
            <tr>
              <td>1,011</td>
              <td>eget</td>
              <td>nulla</td>
              <td>Class</td>
              <td>aptent</td>
            </tr>
            <tr>
              <td>1,012</td>
              <td>taciti</td>
              <td>sociosqu</td>
              <td>ad</td>
              <td>litora</td>
            </tr>
            <tr>
              <td>1,013</td>
              <td>torquent</td>
              <td>per</td>
              <td>conubia</td>
              <td>nostra</td>
            </tr>
            <tr>
              <td>1,014</td>
              <td>per</td>
              <td>inceptos</td>
              <td>himenaeos</td>
              <td>Curabitur</td>
            </tr>
            <tr>
              <td>1,015</td>
              <td>sodales</td>
              <td>ligula</td>
              <td>in</td>
              <td>libero</td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="https://getbootstrap.com/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<script src="{% static 'misgastos/js/dashboard.js' %}"></script>
</body>
</html>

templates/test.html
{% extends "base.html" %}

{% block content %}

	<h1>You are logged in!</h1>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}

{% block content %}

	<h1>Thanks for visiting, come back soon!</h1>

{% endblock %}