accountsapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accountsapp'

urlpatterns = [
	path('login/',auth_views.LoginView.as_view(template_name='accountsapp/login.html'), name='login'),
	path('change-password/',auth_views.PasswordChangeView.as_view(template_name='accountsapp/change-password.html', success_url='/'), name='change_password'),
	path('logout/',auth_views.LogoutView.as_view(), name='logout'),
	path('signup/',views.SignUpView.as_view(), name='signup'),
	#path('update_profile/<int:pk>/',views.UpdateProfile.as_view(), name='update_profile'),
	path('update_profile/',views.UpdateProfile.as_view(), name='update_profile'),
	path('create_profile/',views.CreateProfile.as_view(), name='create_profile'),
	path('list_profile/',views.ListProfile.as_view(),name='list_profile')
]

budgetsapp/urls.py
from django.urls import path
from . import views
from expensesapp import views as expenses_views

app_name = 'presupuestos'

urlpatterns = [
	path('',views.ListBudget.as_view(),name='all'),
	path('create/',views.CreateBudget.as_view(),name='create'),
	path('<int:pk>/gastos/create/',expenses_views.CreateExpense.as_view(),name='create_expense'),
	path('update/<int:pk>/',views.UpdateBudget.as_view(),name='update'),
	path('delete/<int:pk>/',views.DeleteBudget.as_view(),name='delete'),
	path('<int:pk>/',views.BudgetDetail.as_view(),name='detail'),
	path('<int:pk>/summary/',views.BudgetDetailTiny.as_view(),name='detail_summary'),
]

expensesapp/urls.py
from django.urls import path
from expensesapp import views

app_name = 'gastos'

urlpatterns = [
	path('update/<int:pk>/',views.UpdateExpense.as_view(),name='update_expense'),
	path('delete/<int:pk>/',views.DeleteExpense.as_view(),name='delete_expense'),
	path('ajax/pay_expense/',views.pay_expense,name='pay_expense'),
	#path('create/',views.CreateExpense.as_view(),name='_create_'),
	#path('expense/create/',views.CreateExpense.as_view(),name='create_expense'),
	#path('<int:pk>/',views.BudgetDetail.as_view(),name='detail'),

]

loanapp/urls.py
from django.urls import path
from loanapp import views

app_name = 'loans'

urlpatterns = [
	path('',views.AboutView.as_view()),
	path('test',views.LoanView.as_view()),
	path('calculadora_uva/',views.LoanQueryView.as_view(), {'cuota':0, 'saldo':0}, name='calculadora'),
	path('clear-cookies', views.clear_cookies),
]

misgastos/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('new/',views.NewHomePage.as_view(),name='new_home'),
    path('accounts/',include('accountsapp.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path("presupuestos/", include("budgetsapp.urls", namespace="presupuestos")),
    path("gastos/", include("expensesapp.urls", namespace="gastos")),
    path("categorias/", include("categoriesapp.urls", namespace="categorias")),
    path("coffees/", include("coffeeApp.urls", namespace="coffee")),
    path("telegramapi/", include("telegramapi.urls", namespace="telegramapi")),
    path("inversiones/", include("investmentapp.urls", namespace="inversiones")),

    path("loans/", include("loanapp.urls", namespace="loans")),
]

budgetsapp/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth import get_user_model
User = get_user_model()

class Budget(models.Model):
	name = models.CharField(max_length=100)
	slug = models.SlugField(allow_unicode=True)
	description = models.CharField(blank=True,default='',max_length=255)
	user = models.ForeignKey(User,related_name='budgets',on_delete=models.PROTECT)
	expired_date = models.DateField(blank=True,null=True)

	def get_absolute_url(self):
		return reverse('presupuestos:all')

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super().save(*args, **kwargs)

budgetsapp/forms.py
from django import forms
from django.utils.text import slugify

from budgetsapp.models import Budget

class BudgetForm(forms.ModelForm):
    budget_choice = forms.ChoiceField()

    class Meta:
        model = Budget
        fields = ('name','description','expired_date')
        
    def __init__(self,*args,**kwargs):
        self.user = kwargs.pop('user')  # To get request.user. Do not use kwargs.pop('user', None) due to potential security hole
        super().__init__(*args, **kwargs)
        # Cristhian:
        # Label in the HTML
        # Optional
        self.fields['name'].label = 'Nombre'
        self.fields['description'].label = 'Breve descripcion'
        self.fields['expired_date'].label = 'Fecha de finalizacion'
        self.fields['expired_date'].widget = forms.DateInput(attrs={'class':'datepicker'})
        
        budgets = Budget.objects.filter(user__username__iexact=self.user.username).order_by('name')
        BUDGETS_CHOICES = [(0,"----")]
        #BUDGETS_CHOICES.extend([ (x+1, budgets[x]) for x in range(0,len(budgets)) ])
        BUDGETS_CHOICES.extend([ (x+1, budgets[x]) for x in range(0,len(budgets)) if budgets[x].expenses.all().count() > 0 ])
        self.fields['budget_choice'].label = 'Copiar gastos'
        self.fields['budget_choice'].choices = BUDGETS_CHOICES

    def clean_name(self):
        data = self.cleaned_data['name']
        data = slugify(data)
        listado = Budget.objects.filter(slug__iexact=data).filter(user__exact=self.user)
        if len(listado) > 0 and self.cleaned_data['name'] != self.instance.name:
            raise forms.ValidationError("Ya hay un presupuesto con ese nombre!")

        return data

budgetsapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views import generic

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils import timezone

from budgetsapp import forms
from budgetsapp.models import Budget
from expensesapp.models import Expense

from django.core.exceptions import PermissionDenied

class ListBudget(LoginRequiredMixin,generic.ListView):
	model = Budget

	def get_queryset(self):
		queryset = super().get_queryset()
		# Fix for django.db.utils.ProgrammingError: can't adapt type 'SimpleLazyObject'
		myuser = str(self.request.user)
		return queryset.filter(user__username__iexact=myuser).order_by('-expired_date')

class CreateBudget(LoginRequiredMixin,generic.CreateView):
	form_class = forms.BudgetForm
	model = Budget

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs.update({'user': self.request.user})
		return kwargs

	def get_context_data(self, **kwargs):
	 	context = super().get_context_data(**kwargs)
	 	budgets = Budget.objects.filter(user__username__iexact=self.request.user).order_by('name')
	 	#context['budgets'] = budgets

	 	return context

	def form_valid(self,form):
		budgets = Budget.objects.filter(user__username__iexact=self.request.user.username).order_by('name')
		BUDGETS_CHOICES = [('0',"----")]
		BUDGETS_CHOICES.extend([ (x+1, budgets[x]) for x in range(0,len(budgets))])
		
		self.object = form.save(commit=False)
		self.object.user = self.request.user
		self.object.save()

		# For copy Expenses from another Budget
		choice = int(form.data['budget_choice'])
		if choice == 0:
			return super().form_valid(form)

		k, previous_budget = BUDGETS_CHOICES[choice]
		previous_budget_name = previous_budget.name
		budgets_list = Budget.objects.filter(user__username__iexact=self.request.user.username).filter(name__iexact=previous_budget_name)
		mybudget = budgets_list[0]

		#listado_expenses = Expense.objects.filter(budget__name__iexact=previous_budget_name)
		listado_expenses = Expense.objects.filter(budget__pk__exact=mybudget.pk)

		for expense in listado_expenses:
			new_expense = Expense()
			new_expense.category_id = expense.category_id
			new_expense.name = expense.name
			new_expense.amount = expense.amount
			new_expense.tarjeta_credito = expense.tarjeta_credito
			new_expense.cantidad_total = expense.cantidad_total
			new_expense.cantidad_pendiente = expense.cantidad_total
			new_expense.skip = False
			if new_expense.tarjeta_credito:
				if expense.cantidad_total == 1:
					new_expense.skip = True
				elif expense.cantidad_pendiente > 0:
					new_expense.cantidad_pendiente = expense.cantidad_pendiente - 1 
				elif expense.cantidad_total > 1:
					continue

			new_expense.gasto = expense.gasto
			new_expense.budget = self.object
			new_expense.save()

		return super().form_valid(form)

class UpdateBudget(LoginRequiredMixin,UserPassesTestMixin,generic.UpdateView):
	form_class = forms.BudgetForm
	model = Budget

	def test_func(self):
		budgets = Budget.objects.filter(pk__exact=self.kwargs.get('pk'))
		if len(budgets) == 1:
			mybudget = budgets[0]

			if mybudget.user.username == self.request.user.username:
				return True

		raise PermissionDenied("You are not authenticated to edit this.")

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs.update({'user': self.request.user})
		return kwargs

class DeleteBudget(LoginRequiredMixin,UserPassesTestMixin,generic.DeleteView):
	model = Budget
	success_url = reverse_lazy('presupuestos:all')
	#select_related = ('user','group')

	def test_func(self):
		budgets = Budget.objects.filter(pk__exact=self.kwargs.get('pk'))
		if len(budgets) == 1:
			mybudget = budgets[0]
			
			if mybudget.user.username == self.request.user.username:
				return True

		raise PermissionDenied("You are not authenticated to edit this.")

	def get_queryset(self):
		queryset = super().get_queryset()
		return queryset.filter(pk=self.kwargs.get('pk'))

	def delete(self,*args,**kwargs):
		messages.success(self.request,'Budget Deleted')
		budgets = Budget.objects.filter(pk__exact=self.kwargs.get('pk')).order_by('name')
		if len(budgets) > 0:
			for expense in budgets[0].expenses.all():
				expense.delete()

		return super().delete(*args,**kwargs)

class BudgetDetail(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
	model = Budget

	def test_func(self):
		budgets = Budget.objects.filter(pk__exact=self.kwargs.get('pk'))
		if len(budgets) == 1:
			mybudget = budgets[0]
			
			if mybudget.user.username == self.request.user.username:
				return True

		raise PermissionDenied("You are not authenticated to edit this.")

	def get_queryset(self):
		queryset = super().get_queryset()
		return queryset.filter(pk__exact=self.kwargs.get('pk'))

	def get_context_data(self, **kwargs):
	 	context = super().get_context_data(**kwargs)
	 	expenses = Expense.objects.filter(budget=self.kwargs.get('pk'))
	 	ingresos = 0
	 	egresos = 0
	 	tarjeta_credito = 0
	 	for expense in expenses:
	 		if expense.skip:
	 			continue

	 		if expense.gasto == True:
	 			if expense.tarjeta_credito == False:
	 				egresos += expense.pending_amount
	 			else:
	 				if expense.is_paid:
	 					tarjeta_credito += round(expense.amount)
	 				else:
	 					tarjeta_credito += expense.pending_amount
	 		else:
	 			ingresos += expense.amount

	 	context['egresos'] = round(egresos,2)
	 	context['ingresos'] = round(ingresos,2)
	 	context['tarjeta_credito'] = round(tarjeta_credito,2)

	 	if self.object.expired_date != None:
	 		fecha = self.object.expired_date - timezone.now().date()
	 		balance = ingresos - egresos
	 		context['days_left'] = fecha.days
	 		if balance > 0:
	 			if fecha.days > 0:
	 				context['balance'] = round(balance / fecha.days,2)
	 			else:
	 				context['balance'] = round(balance,2)
	 		else:
	 			context['balance'] = 0
	 	else:
	 		context['days_left'] = ""

	 	return context

class BudgetDetailTiny(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
	model = Budget
	template_name = 'budgetsapp/budget_detail_summary.html'

	def test_func(self):
		budgets = Budget.objects.filter(pk__exact=self.kwargs.get('pk'))
		if len(budgets) == 1:
			mybudget = budgets[0]
			
			if mybudget.user.username == self.request.user.username:
				return True

		raise PermissionDenied("You are not authenticated to edit this.")

	def get_queryset(self):
		queryset = super().get_queryset()
		return queryset.filter(pk__exact=self.kwargs.get('pk'))

	def get_context_data(self, **kwargs):
	 	context = super().get_context_data(**kwargs)
	 	expenses = Expense.objects.filter(budget=self.kwargs.get('pk'))
	 	ingresos = 0
	 	egresos = 0
	 	tarjeta_credito = 0
	 	egresos_pendientes = 0
	 	non_paid_expenses = Expense.objects.filter(budget=self.kwargs.get('pk')).filter(cantidad_pendiente__gt=0).filter(tarjeta_credito=False).filter(skip=False)
	 	for expense in expenses:
	 		if expense.skip:
	 			continue
	 			
	 		if expense.gasto == True:
 				if expense.tarjeta_credito == False:
	 				egresos += expense.get_amount
	 				egresos_pendientes += expense.pending_amount
	 			else:
	 				tarjeta_credito += expense.get_amount
	 		else:
	 			ingresos += expense.get_amount

	 	context['egresos'] = round(egresos, 2)
	 	context['ingresos'] = round(ingresos, 2)
	 	if self.object.expired_date != None:
	 		fecha = self.object.expired_date - timezone.now().date()
	 		balance = ingresos - egresos - egresos_pendientes
	 		context['days_left'] = fecha.days
	 		if balance > 0:
	 			if fecha.days > 0:
	 				context['balance'] = round(balance / fecha.days,2)
	 			else:
	 				context['balance'] = round(balance,2)
	 		else:
	 			context['balance'] = 0
	 	else:
	 		context['days_left'] = ""

	 	context['non_paid_expenses'] = non_paid_expenses
	 	context['egresos_pendientes'] = round(egresos_pendientes, 2)

	 	return context

budgetsapp/templates/budgetsapp/budget_confirm_delete.html
{% extends "budgetsapp/budget_base.html" %}

{% block group_content %}
	<h3>¿Seguro desea borrar ?</h3>

	<form method="POST">
		{% csrf_token %}
		<input type="submit" class="btn btn-danger btn-large" value="Confirm Delete">
		<a class='btn btn-info btn-large' href="{% url 'presupuestos:detail' pk=budget.pk %}">Cancel</a>
	</form>

{% endblock %}

budgetsapp/templates/budgetsapp/budget_detail.html
{% extends "budgetsapp/budget_base.html" %}
{% load bootstrap3 %}

{% block pregroup %}
  <div class="col">
		<h1>{{ budget.name|title }}</h1>
		<h5>{{ budget.description }}</h5>
    <a href="{% url 'presupuestos:update' pk=budget.pk %}" class='btn btn-md btn-fill btn-warning'>Modificar</a>
    <a href="{% url 'presupuestos:delete' pk=budget.pk %}" class='btn btn-md btn-fill btn-danger'>Eliminar</a>
	</div>
  <div class="col my-auto">
    <a href="{% url 'presupuestos:detail_summary' pk=budget.pk %}">
      <input type="submit" class='btn btn-primary btn-large' value="Cuenta regresiva">  
    </a>
  </div>
{% endblock %}

{% block postgroup %}
	
	<div class="col order-1">
    <div class="alert alert-success" id="ingresos" role="alert">
      Ingresos: {{ ingresos }}
    </div>
    <div class="alert alert-danger" id="egresos" role="alert">
        Egresos: {{ egresos }}
    </div>
    <div class="alert alert-danger" id="tarjeta_credito" role="alert">
        Tarjeta de Credito: {{ tarjeta_credito }}
    </div>
	</div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script>
      function updateCounters(){
        var ingresos = {{ ingresos }};
        var ingresos_string = ingresos.toString();
        var i = 0;
        var factor = ingresos / ingresos_string.length / 10 ;
        
        refreshId_ingresos = setInterval(function(){ 
          i = i + factor;
          if(i < ingresos) {
            $("#ingresos").html("Ingresos: " + i.toFixed(2)); 
          }
          else {
            $("#ingresos").html("Ingresos: " + ingresos); 
            clearInterval(refreshId_ingresos);
          }
        }, 1 * 50);


        var egresos = {{ egresos }};
        var egresos_string = egresos.toString();
        var i = 0;
        var factor_egresos = egresos / egresos_string.length / 10 ;
        refreshId_egresos = setInterval(function(){ 
          i = i + factor_egresos;
          if(i < egresos) {
            $("#egresos").html("Egresos: " + i.toFixed(2)); 
          }
          else {
            $("#egresos").html("Egresos: " + egresos); 
            clearInterval(refreshId_egresos);
          }
        }, 1 * 50)


        var egresos_tc = {{ tarjeta_credito }};
        var egresos_tc_string = egresos_tc.toString();
        var i = 0;
        var factor_egresos_tc = egresos_tc / egresos_tc_string.length / 10 ;
        refreshId_egresos_tc = setInterval(function(){ 
          i = i + factor_egresos_tc;
          if(i < egresos_tc) {
            $("#tarjeta_credito").html("Tarjeta de Credito: " + i.toFixed(2)); 
          }
          else {
            $("#tarjeta_credito").html("Tarjeta de Credito: " + egresos_tc); 
            clearInterval(refreshId_egresos_tc);
          }
        }, 1 * 50)
      }
      updateCounters()

  </script>

{% endblock %}

{% block footer %} 
  <div class="container-fluid">
    <table class="table table-striped order-list">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Titulo</th>
          <th scope="col">Categoria</th>
          <th scope="col">Monto</th>
          <th scope="col">Gasto</th>
          <th scope="col">Tarjeta Credito</th>
          <th align="center">Pagado</th>
          <th align="center">Edit</th>
          <th align="center">Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for expense in budget.expenses.all %}
            <tr id={{ expense.pk }} >
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{expense.name}}</td>
              <td>{{expense.category}}</td>
              <td>{{expense.total_amount}}</td>
              <td>
                {% if expense.gasto == True %}
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input" disabled="true" checked>
                    <label class="form-check-label"></label>
                  </div>
                {% else %}
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input" disabled="true">
                    <label class="form-check-label"></label>
                  </div>
                {% endif %}
              </td>
              <td>
                {% if expense.tarjeta_credito == True %}
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input" disabled="true" checked>
                    <label class="form-check-label"></label>
                  </div>
                {% else %}
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input" disabled="true">
                    <label class="form-check-label"></label>
                  </div>
                {% endif %}
              </td>
              <td>
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                    {% if expense.skip %}
                      <button type="button" class="btn btn-info btn-custom-class" disabled="true">Skipped</button> 
                    {% elif expense.gasto != True %}
                      <button type="button" class="btn btn-primary btn-custom-class" disabled="true">Ingreso</button> 
                    {% elif expense.is_paid == True %}
                      <button type="button" class="btn btn-success btn-custom-class" disabled="true">Pagado</button> 
                    {% elif expense.is_credit_card == True %}
                      <button type="button" class="btn btn-secondary btn-custom-class" disabled="true">Credit Card ( {{expense.cantidad_pendiente }})</button> 
                    {% else %}
                      <button type="button" class="btn btn-danger btn-custom-class">Pendiente ( {{expense.cantidad_pendiente }})</button>
                    {% endif %}
                </div>
              </td>
              <td align="left">
                <a href="{% url 'gastos:update_expense' pk=expense.pk %}">
                  <i class='fas fa-pencil-alt' alt="Editar"></i>
                </a>
              </td>
              <td align="left">
                <a href="{% url 'gastos:delete_expense' pk=expense.pk %}">
                  <i class='far fa-trash-alt' alt="Eliminar"></i>
                </a>
                
              </td>
            </tr>
        {% endfor %}
      </tbody>
    </table>

  <script>
        $(".btn-custom-class").on('click', function(event) {
          
            //$(this).removeClass("btn-success")
            //$(this).addClass("btn-danger")
            //$(this).text("Pendiente")
            //console.log("Removed class")  
          //}
          if( $(this).hasClass("btn-danger") ){
            
            var previous_text = $(this).text()

            $(this).attr('disabled', true)
            $(this).text("In progress...")

            var myid = $(this).closest('tr').attr('id')

            $(this).animate({
              opacity: '0.5',
            });

            if( $(this).hasClass("btn-danger") ){
              
              var _self_ = $(this)
              $.ajax({
                type:"POST",
                url: "{% url 'gastos:pay_expense'%}",               //url: '/ajax/validate_username/',
                data: {
                  csrfmiddlewaretoken: "{{ csrf_token }}", 
                  'myid': myid
                },
                dataType: 'json',
                success: function (data) {
                  if (data.ajax_answer) {
                    if ( data.cantidad_pendiente == '0') {
                      $(_self_).removeClass("btn-danger")
                      $(_self_).addClass("btn-success")
                      $(_self_).text("Pagado")
                    }
                    else
                    {
                      $(_self_).text("Pendiente ( " + data.cantidad_pendiente + " )") 
                      $(_self_).attr('disabled', false)
                      $(_self_).animate({
                        opacity: '1',
                      });
                    }

                  }
                  else {
                    alert('Unable to update.')
                    $(_self_).attr('disabled', false)
                    $(_self_).text(previous_text)
                  }
                  
                  $(_self_).animate({
                      opacity: '1',
                    });
                    
                },
                error: function (request, status, error) {
                      window.location.href = "{% url 'accountsapp:login' %}"
                  }

              });


              //$(this).removeClass("btn-danger")
              //$(this).addClass("btn-success")
              //$(this).text("Pagado")
            }

          }

            event.preventDefault()
        });

    </script>
    <a href="{% url 'presupuestos:create_expense' pk=budget.pk %}" class='btn btn-md btn-fill btn-primary'>
          Crear nuevo ingreso / gasto
        </a>
  </div>
{% endblock %}

budgetsapp/templates/budgetsapp/budget_detail_summary.html
{% extends "budgetsapp/budget_base.html" %}
{% load bootstrap3 %}

{% block pregroup %}
  <div class="col">
		<h1>{{ budget.name|title }}</h1>
		<h5>{{ budget.description }}</h5>
    <a href="{% url 'presupuestos:update' pk=budget.pk %}" class='btn btn-md btn-fill btn-warning'>Modificar</a>
    <a href="{% url 'presupuestos:delete' pk=budget.pk %}" class='btn btn-md btn-fill btn-danger'>Eliminar</a>
	</div>
  <div class="col my-auto">
    <a href="{% url 'presupuestos:detail' pk=budget.pk %}">
      <input type="submit" class='btn btn-primary btn-large' value="Detalle">  
    </a>
  </div>
{% endblock %}

{% block postgroup %}
	
	<div class="col order-1">
    {% if balance > 0 %}
      <div class="alert alert-success" id="balance" role="alert">
        Balance ( Disponible para gastar por día ): {{ balance }}      
      </div>
    {% else %}
      <div class="alert alert-danger" id="balance" role="alert">
        Balance ( Faltante por día ) : {{ balance }}      
      </div>
    {% endif %}
    <div class="alert alert-danger" id="balance" role="alert">
        Gastos Pendientes : {{ egresos_pendientes }}      
      </div>
    <div class="alert alert-info" id="daysleft" role="alert">
        Dias Faltantes: {{ days_left }}
    </div>
	</div>

  {% if days_left == '' %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>
        var ingresos = {{ ingresos }};
        var ingresos_string = ingresos.toString();
        var i = 0;
        var factor = ingresos / ingresos_string.length / 10 ;
        refreshId_ingresos = setInterval(function(){ 
          i = i + factor;
          if(i < ingresos) {
            $("#ingresos").html("Ingresos: " + i); 
          }
          else {
            $("#ingresos").html("Ingresos: " + ingresos); 
            clearInterval(refreshId_ingresos);
          }
        }, 1 * 10);

        var egresos = {{ egresos }};
        var egresos_string = egresos.toString();
        var i = 0;
        var factor_egresos = egresos / egresos_string.length / 10 ;
        refreshId_egresos = setInterval(function(){ 
          i = i + factor_egresos;
          if(i < egresos) {
            $("#egresos").html("Egresos: " + i); 
          }
          else {
            $("#egresos").html("Egresos: " + egresos); 
            clearInterval(refreshId_egresos);
          }
        }, 1 * 10)

    </script>
  {% endif %}

{% endblock %}

{% block footer %} 
  <div class="container-fluid">
    <table class="table table-striped order-list">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Titulo</th>
          <th scope="col">Categoria</th>
          <th scope="col">Cantidad</th>
          <th scope="col">Monto</th>
          <th scope="col">Gasto</th>
          <th scope="col">Tarjeta Credito</th>
          <th align="center">Edit</th>
          <th align="center">Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for expense in non_paid_expenses %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{expense.name}}</td>
              <td>{{expense.category}}</td>
              <td>{{expense.cantidad_pendiente}}</td>
              <td>{{expense.pending_amount}}</td>
              <td>
                {% if expense.gasto == True %}
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input" disabled="true" checked>
                    <label class="form-check-label"></label>
                  </div>
                {% else %}
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input" disabled="true">
                    <label class="form-check-label"></label>
                  </div>
                {% endif %}
              </td>
              <td>
                {% if expense.tarjeta_credito == True %}
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input" disabled="true" checked>
                    <label class="form-check-label"></label>
                  </div>
                {% else %}
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input" disabled="true">
                    <label class="form-check-label"></label>
                  </div>
                {% endif %}
              </td>
              <td align="left">
                <a href="{% url 'gastos:update_expense' pk=expense.pk %}">
                  <i class='fas fa-pencil-alt' alt="Editar"></i>
                </a>
              </td>
              <td align="left">
                <a href="{% url 'gastos:delete_expense' pk=expense.pk %}">
                  <i class='far fa-trash-alt' alt="Eliminar"></i>
                </a>
                
              </td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'presupuestos:create_expense' pk=budget.pk %}" class='btn btn-md btn-fill btn-primary'>
          Crear nuevo ingreso / gasto
        </a>
  </div>
  
{% endblock %}